site_name: Model Modem
nav:
  - About: index.md
  - Development:
    - Cheat Codes: dev/cheat-codes.md
    - Python: 
      - pip: dev/py/pip.md
    - PHP:
      - Official Docker: dev/php/official-docker.md
    - MKDocs: dev/mkdocs.md
  - Technology:
    - My Stack: tech/my-stack.md


# Site Customizations
extra_css:
  - assets/css/extra.css
theme:
  name: material
  custom_dir: theme_overrides
  palette: 
    scheme: slate
  font:
    code: Fira Code
    text: Montserrat
  icon:
    logo: material/alpha-m-circle
  features:
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  disqus: modelmodem-com
  social: 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/djsipe/ 
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.details
  - admonition
  - attr_list